# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677c5c1cc06760862a3e6df2d0894d99cc92549dccfc8c4fce87b376e2ac7137f4c0a850270142c75f8b55022a71b884298645288d22b5c25b79a37e6dd00520

test:
  secret_key_base: 3295909f33dbe2547ca238221a355b4a0b15c78afb7eca531695d8ef9ceec3970494570cc1539da1d962bf8cbd530e82e9df0e2c036686cae2e876b6e04aa8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
